### ISSUE TITLE
Accessing /viewers when not logged in causes server error

### ISSUE THREAD

**Issue by vdikun** [vdikun/travelog#17]
The traceback:

`Traceback (most recent call last):
  File "/media/vera/1703f7c8-9f5b-4fb7-bc9a-cac43729234c/home/vera/workspace/travelog/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/media/vera/1703f7c8-9f5b-4fb7-bc9a-cac43729234c/home/vera/workspace/travelog/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/media/vera/1703f7c8-9f5b-4fb7-bc9a-cac43729234c/home/vera/workspace/travelog/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
    return original_handler(e)
  File "/media/vera/1703f7c8-9f5b-4fb7-bc9a-cac43729234c/home/vera/workspace/travelog/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/media/vera/1703f7c8-9f5b-4fb7-bc9a-cac43729234c/home/vera/workspace/travelog/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/vera/1703f7c8-9f5b-4fb7-bc9a-cac43729234c/home/vera/workspace/travelog/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/vera/1703f7c8-9f5b-4fb7-bc9a-cac43729234c/home/vera/workspace/travelog/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
    return original_handler(e)
  File "/media/vera/1703f7c8-9f5b-4fb7-bc9a-cac43729234c/home/vera/workspace/travelog/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/media/vera/1703f7c8-9f5b-4fb7-bc9a-cac43729234c/home/vera/workspace/travelog/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/vera/1703f7c8-9f5b-4fb7-bc9a-cac43729234c/home/vera/workspace/travelog/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/vera/1703f7c8-9f5b-4fb7-bc9a-cac43729234c/home/vera/workspace/travelog/venv/lib/python2.7/site-packages/flask_login.py", line 755, in decorated_view
    return func(*args, **kwargs)
  File "/media/vera/1703f7c8-9f5b-4fb7-bc9a-cac43729234c/home/vera/workspace/travelog/views/default.py", line 102, in makeviewers
    viewers = find_viewers(current_user)
  File "/media/vera/1703f7c8-9f5b-4fb7-bc9a-cac43729234c/home/vera/workspace/travelog/models/user/user.py", line 30, in find_viewers
    Viewer.o_id == owner.id)
  File "/media/vera/1703f7c8-9f5b-4fb7-bc9a-cac43729234c/home/vera/workspace/travelog/venv/lib/python2.7/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'`

The expected result is a "cannot access while logged out" page.

**Comment by vdikun** [comment]
This is a low priority issue. A higher priority is hiding the /viewers page from users who are themselves viewers (i.e. cannot give viewing permissions to anyone).
